version: '3.8'

services:


################################
# Web
################################
  web_app:
    build: .
    image: flask/celery:v1
    container_name: web_app
    ports:
      - 5004:5000
    command: "python app.py run -h 0.0.0.0"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=routes.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

################################
# Celery Worker
################################
  worker_app:
    build: .
    command: celery worker --app=routes.server.tasks.celery --loglevel=info --logfile=routes/logs/celery/celery.log
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=routes.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web_app
      - redis

################################
# Celery monitor
################################
  flower_app:
    build: .
    container_name: flower_app
    command: flower --app=routes.server.tasks.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=routes.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web_app
      - redis
      - worker_app

################################
# Message Queue & Result Backend
################################
  redis:
    image: redis:6.0-alpine
    container_name: redis_app
    restart: always
    volumes:
      - ./routes/logs/redis:/data
      - ./routes/logs/redis:/usr/local/etc/redis

networks:
  default:
    name: flask-celery-networks